version: "3.9"
networks:
  phrankennet:
    driver: bridge

services:
  fknapp:
    image: dunglas/frankenphp:latest
    container_name: laravel_app
    ports:
      - "8201:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/storage/logs:/var/www/html/storage/logs
    environment:
      - FRANKENPHP_MODE=octane
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - fkndb
    networks:
      - phrankennet

  fkndb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "30601:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pranksecret
      MYSQL_DATABASE: prankdb
      MYSQL_USER: prankuser
      MYSQL_PASSWORD: pranky
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - networkName: phrankennet

  fkndbman:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "18201:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pranksecret
    depends_on:
      - fkndb
    networks:
      - phrankennet

volumes:
  mariadb_data:
