networks:
  frankennet:
    driver: bridge

services:
  frankenapp:
    container_name: frankenapp
    build: .
    # restart: always
    volumes:
      - ./app:/app
    ports:
      - "10800:80"
      - "10400:443"
      - "10400:443/udp"
    tty: true
    depends_on:
      - frankendbm
    networks:
      - frankennet

  frankendbm:
    container_name: frankendbm
    image: mariadb
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: frankenize
      MYSQL_DATABASE: frankendb
      MYSQL_USER: frankenize
      MYSQL_PASSWORD: frankenize
    networks:
      - frankennet
    ports:
      - "10300:3306"

  frankenpma:
    container_name: frankenpma
    image: phpmyadmin/phpmyadmin
    # restart: always
    environment:
      PMA_HOST: frankendbm
      PMA_USER: frankenize
      PMA_PASSWORD: frankenize
    ports:
      - "10600:80"
    depends_on:
      - frankendbm
    networks:
      - frankennet
